name: 'Check #include guards'

on:
  push:
    paths:
    - '.github/workflows/includeguards.yml'
    - 'src/devices/**.h'
    - 'src/mame/**.h'
  pull_request:
    paths:
    - '.github/workflows/includeguards.yml'
    - 'src/devices/**.h'
    - 'src/mame/**.h'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Validate
      run: python3 scripts/build/check_include_guards.py src/devices src/mame
